# Generated by Django 4.0.2 on 2023-02-24 02:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_agency_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='phone',
            field=models.BigIntegerField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 2, 27, 55, 663817, tzinfo=utc)),
        ),
    ]
