# Generated by Django 4.0.2 on 2023-04-26 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_agency_email_agency_phone_alter_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 18, 39, 56, 277864, tzinfo=utc)),
        ),
    ]
